import Head from "next/head";
import DisplayFrontCard from "../components/Card";

export default function Home() {
  return (
    <div className="w-full pb-10">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center justify-center flex-col p-10 mt-7 mb-7 h-[30vh]">
        <p className="text-3xl font-bold">
          Thinking of a vacation? Plan
          <span className="text-blue-500 text-3xl">Up</span>!
        </p>
      </div>

      <div className="flex items-center justify-center">
        <div className="grid md:grid-cols-3 grid-cols-1 place-content-center gap-4 px-3">
          <DisplayFrontCard
            img={"/map.jpeg"}
            title={"Destination Finder"}
            description={
              "Find the perfect destination with our AI destination finder tool"
            }
            href={"/destination"}
          />
          <DisplayFrontCard
            img={"/plan.jpg"}
            title={"Itinerary Planner"}
            description={
              "Get the perfect detailed plan for your trip with our AI itinerary planner"
            }
            href={"/itinerary"}
          />
        </div>
      </div>
    </div>
  );
}
